#-------------------------------
# General Site Settings

menu:
- {name: 'About', url: 'pages/about.html'}
- {name: 'Projects', url: ''}
- {name: 'Resume', url: 'pages/resume.html'}
- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >

contact: >
  # Contact

  Feel free to  contact me via [email](mailto:soham.ghormade@gmail.com) if you are interested in learning more about my projects.

#-------------------------------
# Work Section

projects:
- {name: 'Computational Photography', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'Robotics:AI Techniques', folder: 'proj-2', file: 'projects/proj-2.html'}
- {name: 'Application Integration', folder: 'proj-3', file: 'projects/proj-3.html'}
- {name: 'Computer Vision', folder: 'proj-4', file: 'projects/proj-4.html'}
- {name: 'Machine Learning', folder: 'proj-5', file: 'projects/proj-5.html'}
- {name: 'Reinforcement Learning', folder: 'proj-6', file: 'projects/proj-6.html'}
- {name: 'Intro to Operating Systems', folder: 'proj-7', file: 'projects/proj-7.html'}
- {name: 'AI Ethics', folder: 'proj-8', file: 'projects/proj-8.html'}
# TODO uncomment sections below in May 2022 and add pages for AI and CN
# - {name: 'Computer Networks', folder: 'proj-9', file: 'projects/proj9.html'}
# - {name: 'AI', folder: 'proj-10', file: 'projects/proj-10.html'}
#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'https://twitter.com/soham_ghormade?lang=en'}
- {icon: 'medium', link: 'https://soham-ghormade.medium.com/'}
- {icon: 'github', link: 'https://github.com/ghormadesoham'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/soham-ghormade/'}
- {icon: 'envelope', link: 'mailto:soham.ghormade@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
